# ===============================================================================
# Custom Build Configuration
# ------------------------------------------------------------------------------
# Project   : ImmortalWrt for MT7981 (Philips HY3000)
# Repository: https://github.com/MomoFlora/immortalwrt-mt7981-philips-hy3000
# Maintainer: Zhao Wenwen
#
# Description:
#   Customized build pipeline based on P3TERX Actions-OpenWrt,
#   tailored for Philips HY3000 platform with MT7981 SoC.
# ===============================================================================

name: 🧩 固件编译

on:
# 远程触发按钮
  repository_dispatch:
  
# 手动触发
  workflow_dispatch:
  
# 定时触发编译
#  schedule:
#    - cron: '10 22 * * 4'


